from amancevice/pandas

RUN pip3 install synapseclient

RUN curl https://raw.githubusercontent.com/sgosline/synapse-workflow-cwl-tools/master/containers/manifest-merge/join_fileview_by_specimen.py > /usr/local/bin/join_fileview_by_specimen.py && chmod a+x /usr/local/bin/join_fileview_by_specimen.py
